# Title of the blog
title: "Igor Kowalczyk Blog"

# Your name
name: "Igor Kowalczyk"

# E-Mail
email: "john@doe.com"

# Description
description: "Blog o technologiach, programowaniu, bezpieczeństwie w sieci i wielu innych rzeczach"

# Link to portfolio (end with slash)
portfolio: "/"

# Main url to the site (end without slash) [or dir.]
url: "https://igorkowalczyk.github.io/"
baseurl: "blog"

# Your github username
github_username: "igorkowalczyk"

# Twitter username
twitter: "@majonezexe"

# Time zone
timezone: "Europe/Warsaw"

# First Launch of the site
first-launch: "2019"

# Support to mobile browsers (It’s unknown what range of browsers support this meta tags) [Better to set the value to "false"!]
mobile: "false"

# Page pagination
paginate: 4

# Markdown and Default theme
markdown: kramdown
theme: minima

# Encoding (default: utf-8)
encoding: utf-8

# RSS Feed config (boolean)
feed:
 enabled: "true"

# Plugins
plugins:
 - jekyll-paginate

# Exclude files
exclude:
 - Gemfile
 - Gemfile.lock
 - feed.xml

# Categories
categories_names:
 "offtop": "Offtop"
 "internet": "Internet"
 "programowanie": "Programowanie"
 "javascript": "JavaScript"

# To comments (only github pr. Replace "igorkowalczyk/blog" with your [username/repo]
comments-post: "https://api-igorkowalczyk.herokuapp.com/v2/entry/igorkowalczyk/blog/master/comments"

# Default branch to comments
staticman:
 branch: "master"

# Captcha - to protect comment. Sitekey - normal key. Secret - encrypted. To encrypt go to https://api-igorkowalczyk.herokuapp.com/v2/encrypt/[YOUR-TEXT-TO-ENCRYPT]
reCaptcha:
 enabled: true
 siteKey: "6LepabEZAAAAACc5CaKQ576otDawf5Zp1HXfCKDu"
 secret: "SBOGLVfiD12mi2BzRmKiNPtbldET2ccrn80DMrIzzxVYdxmM4FfR64w8GjotSPF9Qm71UlyNU3QOojzYdkPq5NF1qSE5e+4wlZ7PLY63nwcQ9jea59RWRIPouBGZRhc5gzbDfQfyQBue32nVFrxXn42Fith81j/1w+aLZjf8AXI="

# Google Tracking ID
# tracking_id: "UA-174454816-2"

# Google Site Verification ID
verification: "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY"

# Arc.io key
arc: "S9mepABR"
