title: Igor Kowalczyk Blog
email: xxmajonezxx@gmail.com
description: Blog na którym pojawiają się wpisy na temat programowania lub innych technologi.
baseurl: "/blog/"
url: "https://igorkowalczyk.github.io/blog"
github_username:  IgorKowalczyk
timezone: 'Europe/Warsaw'
paginate: 8
markdown: kramdown
theme: minima
plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-timeago 
exclude:
 - Gemfile
 - Gemfile.lock
categories_names:
 'offtop': "Offtop"
 'internet': "Internet"
 'programowanie': "Programowanie"
 'javascript': "JavaScript"
 
staticman_url: https://api.staticman.net/v3/entry/github/igorkowalczyk/blog/master/comments

staticman:
  branch: "master"
  
reCaptcha:
  enabled: true
  siteKey: "6LfLAjwUAAAAAKOi8qdESCsIsuNKQWprkVwVTOca"
  secret: "hIjDAFgRYCqZ5vLwealMOgQ27fwTpIh64Wjem8fI6rzs65k6Jr6hDh5A8cTv1gi0LBnc74abCXCUR+hi9lKnozMxnisI2vLnFfcZQYfVCqXyH0d4APJDJJ0qhMxkM6OztcHNx7PjHqms0u4cjVIU1McmbDuxaB02V6z1eMzmdmE="

github_repo_url: https://github.com/igorkowalczyk/blog/